# syntax=docker/dockerfile:1
services:
  users-service:
    container_name: user-service
    build:
      dockerfile: products.Dockerfile
      context: ./users
    ports:
      - 4001:4001
    environment:
      - PORT=4001
      - PG_DB=ecommerce_api
      - PG_PASSWORD=example
      - PG_PORT=5432
      - PG_USER=postgres
    depends_on:
      - db
    restart: always

  cart-service:
    container_name: cart-service
    build:
      dockerfile: products.Dockerfile
      context: ./cart
    ports:
      - 4003:4003
    environment:
      - PORT=4003
      - PG_DB=ecommerce_api
      - PG_PASSWORD=example
      - PG_PORT=5432
      - PG_USER=postgres
    depends_on:
      - db
    restart: always

  products-service:
    container_name: products-service
    build:
      dockerfile: products.Dockerfile
      context: ./products
    ports:
      - 4002:4002
    environment:
      - PORT=4002
      - PG_DB=ecommerce_api
      - PG_PASSWORD=example
      - PG_PORT=5432
      - PG_USER=postgres
    depends_on:
      - db
    restart: always

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ecommerce_api
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    expose:
      - 5432
