// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewUser struct {
	Name string `json:"name"`
}

type User struct {
	ID        string  `json:"id"`
	Name      string  `json:"name"`
	BirthDate *string `json:"birthDate"`
	Street    *string `json:"street"`
}

func (User) IsEntity() {}
