name: build-docker-action
#on:
#  push:
#    branches:
#      - main
#set environment variables
env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  APP_NAME: ${{ 'ecommercepawel' }}


on: [push]
jobs:
  create-dockers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build products
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./products.Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/ecommerce-api-products:latest

      - name: Build users
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./users.Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/ecommerce-api-users:latest

      - name: Build cart
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./cart.Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/ecommerce-api-cart:latest

      - name: Build web
        uses: docker/build-push-action@v2
        with:
          context: ./web
          file: ./web/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/ecommerce-api-web:latest

  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-18.04
    steps:

      # Clone the repository
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Push the Docker image to Heroku Container Registry
      - name: Publish
        run: |
          heroku container:push koniol/ecommerce-api-products -a $APP_NAME
          heroku container:release koniol/ecommerce-api-products -a $APP_NAME