name: build-docker-action
#on:
#  push:
#    branches:
#      - main
on: [push]
jobs:
  create-dockers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install node dependencies
        working-directory: web
        run: npm install
